version: '2'
services:
  nginx:
    build: .
    image: vasyharan/website:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl/private:/etc/ssl/private
