version: '3.2'
services:
  nginx:
    build: ./
    image: vasyharan/nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - type: volume
        source: data-letsencrypt
        target: /etc/letsencrypt
      - type: bind
        source: /etc/ssl/private
        target: /etc/ssl/private
    links:
      - gogs
  gogs:
    image: gogs/gogs
    volumes:
      - type: volume
        source: data-gogs
        target: /data

volumes:
  data-gogs:
  data-letsencrypt:
