version: '3'
services:
  nginx:
    build: .
    image: vasyharan/website:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl/private:/etc/ssl/private
    links:
      - gogs
  gogs:
    image: gogs/gogs
    volumes:
      - /srv/gogs:/data
