# docker run -d --name website -p 80:80 -p 443:443 -v /etc/letsencrypt:/etc/letsencrypt -v /etc/ssl/private:/etc/ssl/private vasyharan/website
version: '2'
services:
  nginx:
    build: .
    image: vasyharan/website:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl/private:/etc/ssl/private
